<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--Include another xacro file-->
<xacro:include filename="$(find robot)/urdf/cylinder_wheel.urdf.xacro"/>

<!--Colors-->
<material name="red">
    <color rgba="1 0 0 1"/>
</material>
<material name="green">
    <color rgba="0 1 0 1"/>
</material>
<material name="black">
    <color rgba="1 1 1 1"/>
</material>

<!--Define new macro xacro-->
<xacro:macro name = "caster_inertial" params = "mass">
    <inertial>
        <mass value = "${mass}"/>
        <inertia ixx = "0.001" ixy = "0" ixz = "0" iyy = "0.001" iyz = "0" izz = "0.001"/>
    </inertial>
</xacro:macro>

<!-- PROPERTY LIST -->
<!-- All units in m-kg-s-radians unit system-->
<xacro:property name = "M_PI" value = "3.1415926535897931"/>
<xacro:property name = "M_PI_2" value = "1.570796327"/>
<xacro:property name = "DEG_TO_RAD" value = "0.017453293"/>

<!-- Main body cylinder base-->
<xacro:property name = "base_height" value = "0.02"/>
<xacro:property name = "base_radius" value= "0.15"/>
<xacro:property name = "base_mass" value = "5"/>

<!-- Caster wheel-->
<xacro:property name = "caster_height" value = "0.04"/>
<xacro:property name = "caster_radius" value = "0.025"/>
<xacro:property name = "caster_mass" value = "0.5"/>

    <!--BASE LINK-->
    <link name = "base_link">
        <visual>
            <geometry>
                <cylinder length = "${base_height}" radius = "${base_radius}"/>            
            </geometry>
            <material name = "green"/>
            <origin rpy = "0 0 0" xyz = "0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length = "${base_height}" radius = "${base_radius}"/>            
            </geometry>
        </collision>
        <xacro:cylinder_inertia m = "${base_mass}" r = "${base_radius}" h = "${base_height}"/>
    </link>

    <!--CYLINDER WHEELS-->
    <xacro:cylinder_wheel fb = "front" lr = "right" parent = "base_link" translateX = "0" translateY = "0.5" flipY = "1"/>
    <xacro:cylinder_wheel fb = "front" lr = "left" parent = "base_link" translateX = "0" translateY = "-0.5" flipY = "1"/>
    
    <!--CASTOR WHEELS-->
    <link name = "caster_front_wheel">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}"/>
            </geometry>
            <material name = "black"/>
            <origin rpy = "${M_PI_2} 0 0" xyz = "0 ${caster_height/2} 0"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster_radius}"/>
                
            </geometry>
            <origin rpy = "${M_PI_2} 0 0" xyz = "0 ${caster_height/2} 0"/>
        </collision>
        <xacro:caster_inertial mass = "${caster_mass}"/>
    </link>

    <link name = "caster_back_wheel">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}"/>
            </geometry>
            <material name = "black"/>
            <origin rpy = "${M_PI_2} 0 0" xyz = "${caster_height/2} ${caster_height/2} 0"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster_radius}"/>
                
            </geometry>
            <origin rpy = "${M_PI_2} 0 0" xyz = "${caster_height/2} ${caster_height/2} 0"/>
        </collision>
        <xacro:caster_inertial mass = "${caster_mass}"/>
    </link>

    <joint name = "caster_front_wheel_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_front_wheel"/>
        <origin rpy = "-${M_PI_2} 0 0" xyz = "0.115 0 0.007"/>
    </joint>

    <joint name = "caster_back_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_back_wheel"/>
        <origin rpy = "-${M_PI_2} 0 0" xyz = "-0.135 0 0.009"/>
    </joint>
    
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
</robot>